"""Repository interfaces and database-neutral implementations."""

from .contracts import (
    AuditRepositoryInterface,
    ChannelRepositoryInterface,
    CheckpointRepositoryInterface,
    CursorRepositoryInterface,
    DeadMediaRepositoryInterface,
    JobRepositoryInterface,
    MetricsRepositoryInterface,
    PostedRepositoryInterface,
    QueueStateRepositoryInterface,
    SubscriptionRepositoryInterface,
    TargetMediaRepositoryInterface,
    WorkerRepositoryInterface,
)
from .legacy import (
    AuditRepository,
    ChannelRepository,
    CheckpointRepository,
    CursorRepository,
    DeadMediaRepository,
    JobRepository,
    MetricsRepository,
    PostedRepository,
    QueueStateRepository,
    SubscriptionRepository,
    TargetMediaRepository,
    TargetRepository,
    WorkerRepository,
)

__all__ = [
    "AuditRepositoryInterface",
    "ChannelRepositoryInterface",
    "CheckpointRepositoryInterface",
    "CursorRepositoryInterface",
    "DeadMediaRepositoryInterface",
    "JobRepositoryInterface",
    "MetricsRepositoryInterface",
    "PostedRepositoryInterface",
    "QueueStateRepositoryInterface",
    "SubscriptionRepositoryInterface",
    "TargetMediaRepositoryInterface",
    "WorkerRepositoryInterface",
    "AuditRepository",
    "ChannelRepository",
    "CheckpointRepository",
    "CursorRepository",
    "DeadMediaRepository",
    "JobRepository",
    "MetricsRepository",
    "PostedRepository",
    "QueueStateRepository",
    "SubscriptionRepository",
    "TargetMediaRepository",
    "TargetRepository",
    "WorkerRepository",
]
