FROM python:3.11-slim

SHELL ["/bin/sh", "-c"]

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONFAULTHANDLER=1 \
    ROYELLS_HUGGINGFACE_SPACE=0 \
    ROYELLS_E2_MICRO_PROFILE=1 \
    ROYELLS_DATA_DIR=/data/royells_media_bot \
    ROYELLS_RUNTIME_DIR=/data/royells_media_bot/runtime \
    ROYELLS_SESSION_DIR=/data/royells_media_bot/runtime/sessions \
    ROYELLS_KEEPALIVE_HTTP=0 \
    ROYELLS_TRY_COPY_MESSAGE=1 \
    ROYELLS_TRY_COPY_MEDIA_GROUP=1 \
    ROYELLS_PRESERVE_ALBUMS=1 \
    ROYELLS_TRY_COPY_ALBUM_ITEMS=0 \
    ROYELLS_SOURCE_ALBUM_INDIVIDUAL_FALLBACK=1 \
    ROYELLS_SOURCE_ALBUM_GROUP_FAILURE_INDIVIDUAL_FALLBACK=1 \
    ROYELLS_SOURCE_ALBUM_SEND_ATTEMPTS=2 \
    ROYELLS_ZERO_BYTE_ITEM_MAX_RETRIES=2 \
    ROYELLS_SOURCE_FAST_COPY=1 \
    ROYELLS_CONTENT_FILTER_ENABLED=0 \
    ROYELLS_ALLOW_AGGRESSIVE_MAIN_WORKERS=0 \
    ROYELLS_DOWNLOAD_WORKERS=1 \
    ROYELLS_UPLOAD_WORKERS=1 \
    ROYELLS_ADAPTIVE_MEDIA_WORKERS=1 \
    ROYELLS_ADAPTIVE_DOWNLOAD_WORKERS_MAX=1 \
    ROYELLS_ADAPTIVE_UPLOAD_WORKERS_MAX=1 \
    ROYELLS_ADAPTIVE_DOWNLOAD_QUEUE_PER_WORKER=4 \
    ROYELLS_ADAPTIVE_UPLOAD_QUEUE_PER_WORKER=25 \
    ROYELLS_ADAPTIVE_WORKER_LOW_WATERMARK=2 \
    ROYELLS_ADAPTIVE_WORKER_INTERVAL_SECONDS=30 \
    ROYELLS_ADAPTIVE_WORKER_COOLDOWN_SECONDS=180 \
    ROYELLS_LINK_WORKERS=1 \
    ROYELLS_BUTTON_WORKERS=2 \
    ROYELLS_TELEGRAM_API_CONCURRENCY=1 \
    ROYELLS_TELEGRAM_DOWNLOAD_CONCURRENCY=1 \
    ROYELLS_TELEGRAM_MEDIA_CONCURRENCY=1 \
    ROYELLS_UPLOAD_ALBUM_CONCURRENCY=1 \
    ROYELLS_MAX_CONCURRENT_TRANSMISSIONS=2 \
    ROYELLS_TELEGRAM_CONTROL_TIMEOUT_SECONDS=15 \
    ROYELLS_TELEGRAM_CONTROL_RETRIES=2 \
    ROYELLS_DOWNLOAD_MEDIA_TIMEOUT_SECONDS=900 \
    ROYELLS_DOWNLOAD_MEDIA_SECONDS_PER_MB=8 \
    ROYELLS_UPLOAD_SEND_TIMEOUT_SECONDS=600 \
    ROYELLS_TELEGRAM_MEDIA_CALL_HARD_TIMEOUT_SECONDS=900 \
    ROYELLS_DOWNLOAD_ATTEMPT_CLEANUP_GRACE_SECONDS=300 \
    ROYELLS_DOWNLOAD_REFRESH_BEFORE_EACH_ITEM=0 \
    ROYELLS_DOWNLOAD_ITEM_API_RETRIES=1 \
    ROYELLS_IN_MEMORY_QUEUE_MAX=24 \
    ROYELLS_UPLOAD_READY_QUEUE_MAX=4 \
    ROYELLS_MEDIA_ADMISSION_BACKPRESSURE_RETRY_SECONDS=10 \
    ROYELLS_SCAN_PREFETCH_PRESSURE_TARGET=16 \
    ROYELLS_QUEUE_RECOVERY_BATCH_LIMIT=50 \
    ROYELLS_QUEUE_RECOVERY_ITEM_DELAY_SECONDS=0.1 \
    ROYELLS_QUEUE_RECOVERY_RETRY_SECONDS=3 \
    ROYELLS_QUEUE_RECOVERY_NOTIFICATIONS=1 \
    ROYELLS_QUEUE_RECOVERY_NOTIFICATION_EDIT_MIN_INTERVAL_SECONDS=300 \
    ROYELLS_QUEUE_RECOVERY_NOTIFICATION_REUSE_SECONDS=86400 \
    ROYELLS_QUEUE_RECOVERY_NOTIFICATION_PERSIST_TIMEOUT_SECONDS=5 \
    ROYELLS_COPY_MESSAGE_ITEM_DELAY=0.05 \
    ROYELLS_ADAPTIVE_INTAKE=1 \
    ROYELLS_ADAPTIVE_INTAKE_START_DELAY_SECONDS=45 \
    ROYELLS_ADAPTIVE_INTAKE_INTERVAL_SECONDS=120 \
    ROYELLS_ADAPTIVE_INTAKE_TIMEOUT_SECONDS=900 \
    ROYELLS_WORKER_STALL_SECONDS=1800 \
    ROYELLS_HISTORICAL_BACKFILL=0 \
    ROYELLS_HISTORICAL_BACKFILL_BATCH_IDS=50 \
    ROYELLS_HISTORICAL_BACKFILL_PRESSURE_TARGET=500 \
    ROYELLS_HISTORICAL_BACKFILL_PAUSE_SECONDS=5 \
    ROYELLS_STARTUP_DEEP_SCAN_EVERY_BOOT=0 \
    ROYELLS_STARTUP_HOT_SCAN_LIMIT=10 \
    ROYELLS_STARTUP_HOT_SCAN_HISTORY_LIMIT=50 \
    ROYELLS_PURGE_DOWNLOADS_ON_BOOT=1 \
    ROYELLS_IMMEDIATE_RESCUE_ENABLED=0 \
    ROYELLS_STARTUP_CATCHUP=0 \
    ROYELLS_AUTO_SYNC=0 \
    ROYELLS_SOURCE_GUARD=0 \
    ROYELLS_AUTO_RECOVERY=0 \
    ROYELLS_LIVE_DASHBOARD=0 \
    ROYELLS_LIVE_DASHBOARD_INTERVAL_SECONDS=300 \
    ROYELLS_TELEGRAM_TRANSPORT_RECOVERY=1 \
    ROYELLS_LARGE_STATE_SAVE_MIN_INTERVAL_SECONDS=90 \
    ROYELLS_SLOW_LOG_RATE_LIMIT_SECONDS=60 \
    ROYELLS_ASYNC_DIAGNOSTICS=0 \
    ROYELLS_CRITICAL_DB_WRITE_QUEUE_LIMIT=5000 \
    ROYELLS_JOB_STATE_DB_QUEUE_LIMIT=5000 \
    ROYELLS_DB_WRITE_BATCH_SIZE=100 \
    ROYELLS_DB_EXECUTOR_WORKERS=1 \
    ROYELLS_PERSISTENCE_EXECUTOR_WORKERS=2 \
    ROYELLS_MEDIA_EXECUTOR_WORKERS=2 \
    ROYELLS_CONTROL_EXECUTOR_WORKERS=2 \
    ROYELLS_CPU_EXECUTOR_WORKERS=1 \
    ROYELLS_TELEGRAM_CONTROL_CONCURRENCY=4 \
    ROYELLS_MAX_RETRIES=4 \
    ROYELLS_SOURCE_JOB_MAX_RETRIES=4 \
    ROYELLS_SOURCE_PERMANENT_RETRY=1 \
    ROYELLS_SOURCE_FAILED_RETRY_DELAY_SECONDS=600 \
    ROYELLS_STARTUP_CATCHUP_DELAY_SECONDS=120 \
    ROYELLS_AUTO_SYNC_CHANNELS_PER_RUN=4 \
    ROYELLS_AUTO_SYNC_HEALTH_CHECK=0 \
    ROYELLS_SOURCE_GUARD_LOOKBACK=80 \
    ROYELLS_SOURCE_GUARD_CATCHUP_LIMIT=800 \
    ROYELLS_SOURCE_GUARD_CHANNELS_PER_TICK=1 \
    ROYELLS_FORCE_RUNTIME_SPEED_PROFILE=1 \
    ROYELLS_SOURCE_GUARD_CHANNEL_TIMEOUT_SECONDS=120 \
    ROYELLS_SOURCE_GUARD_ACCESS_BACKOFF_SECONDS=3600 \
    ROYELLS_TARGET_MEDIA_INDEX=1 \
    ROYELLS_TARGET_MEDIA_INDEX_START_DELAY_SECONDS=7200 \
    ROYELLS_TARGET_MEDIA_INDEX_INTERVAL_SECONDS=86400 \
    ROYELLS_TARGET_MEDIA_INDEX_DELETE_DUPLICATES=1 \
    ROYELLS_KEEPALIVE_SELF_PING=1 \
    ROYELLS_KEEPALIVE_PUBLIC_SELF_PING=0 \
    ROYELLS_KEEPALIVE_LOCAL_SELF_PING=1 \
    ROYELLS_KEEPALIVE_PING_INTERVAL_SECONDS=240 \
    ROYELLS_KEEPALIVE_RATE_LIMIT_BACKOFF_SECONDS=3600 \
    ROYELLS_STARTUP_SOURCE_PEER_WARMUP_LIMIT=20 \
    ROYELLS_SOURCE_DIALOG_SCAN_ON_CACHE_MISS=1 \
    ROYELLS_CHANNEL_PEER_INVALID_BACKOFF_SECONDS=300 \
    ROYELLS_CHANNEL_RETIRE_ON_PEER_INVALID=0 \
    ROYELLS_SCAN_ALBUM_PREFETCH_MIN_INTERVAL_SECONDS=3 \
    ROYELLS_SCAN_ALBUM_PREFETCH_CACHE_SECONDS=900 \
    ROYELLS_PROCESSING_CACHE_TTL_SECONDS=86400 \
    ROYELLS_LOG_MAX_MB=20 \
    ROYELLS_LOG_BACKUP_COUNT=5 \
    ROYELLS_DB_JOURNAL_MODE=WAL \
    ROYELLS_DB_SYNCHRONOUS=NORMAL \
    ROYELLS_DB_HEALTH_CHECK_INTERVAL_SECONDS=120 \
    ROYELLS_DB_ONLINE_RECOVERY_COOLDOWN_SECONDS=120 \
    ROYELLS_DB_OPEN_RETRY_ATTEMPTS=8 \
    ROYELLS_DB_OPEN_RETRY_BASE_SECONDS=0.35 \
    ROYELLS_DB_STARTUP_READY_ATTEMPTS=12 \
    ROYELLS_DB_STARTUP_READY_DELAY_SECONDS=1.5 \
    ROYELLS_DB_OPEN_STARTUP_SIDECAR_REPAIR=1 \
    ROYELLS_RUNTIME_CHECKPOINT=1 \
    ROYELLS_RUNTIME_CHECKPOINT_INTERVAL_SECONDS=15 \
    ROYELLS_RUNTIME_CHECKPOINT_CONFIRM_HISTORY_LIMIT=1000 \
    ROYELLS_RUNTIME_CHECKPOINT_MAX_AGE_DAYS=30 \
    ROYELLS_DELIVERY_AMBIGUITY_GRACE_SECONDS=120 \
    ROYELLS_JSON_FSYNC=1 \
    ROYELLS_DB_RECOVERY_ARTIFACT_KEEP=3 \
    ROYELLS_HARD_WATCHDOG=1 \
    ROYELLS_V21_MICRO_WORKERS=1 \
    ROYELLS_V21_CLEANUP_STALE_TEMP_ON_BOOT=1 \
    ROYELLS_V21_EVENT_QUEUE_SIZE=2000 \
    ROYELLS_V21_BACKPRESSURE_UPLOAD_QUEUE_HIGH=3 \
    ROYELLS_V20_ENABLED=1 \
    ROYELLS_V20_DEPENDENCY_INJECTION=1 \
    ROYELLS_V20_WORKER_REFACTOR=1 \
    ROYELLS_V20_READINESS=1 \
    USE_SQLITE=1 \
    USE_JSON_STATE=1 \
    USE_SQLITE_QUEUE=1 \
    USE_SQLITE_CHECKPOINT=1 \
    USE_POSTGRES=0 \
    USE_REDIS_STATE=0 \
    USE_REDIS_QUEUE=0 \
    USE_REDIS_CHECKPOINT=0 \
    ENABLE_POSTGRES_ADAPTER=0 \
    ENABLE_REDIS_ADAPTER=0 \
    ENABLE_DUAL_WRITE=0 \
    ENABLE_DUAL_READ=0 \
    ENABLE_MIGRATION_LOG=0 \
    ENABLE_ROLLBACK=0 \
    ROYELLS_MAX_BULK_SOURCE_CHANNELS=100 \
    ROYELLS_ADD_CHANNEL_RESOLVE_TIMEOUT_SECONDS=180 \
    ROYELLS_BULK_SOURCE_RESOLVE_TIMEOUT_SECONDS=180 \
    ROYELLS_SLOW_DB_SECONDS=0.5 \
    ROYELLS_SLOW_API_SECONDS=5 \
    ROYELLS_SLOW_MEDIA_SECONDS=15 \
    ROYELLS_EVENT_LOOP_LAG_LOG_SECONDS=1 \
    ROYELLS_RESTORE_MAX_MEMBERS=500 \
    ROYELLS_RESTORE_MAX_UNCOMPRESSED_MB=2048 \
    ROYELLS_POST_DELAY=0 \
    ROYELLS_SUPPORT_COOLDOWN_SECONDS=0 \
    ROYELLS_SUPPORT_DELETE_INCOMING=0 \
    ROYELLS_SUPPORT_USER_MESSAGE_DELETE_DELAY_SECONDS=3600

RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m -u 1000 user \
    && mkdir -p /data \
    && chmod 777 /data

USER user
ENV HOME=/home/user \
    PATH=/home/user/.local/bin:$PATH

WORKDIR $HOME/app

COPY --chown=user requirements.txt ./requirements.txt
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

COPY --chown=user royells_media_bot_ready.py ./royells_media_bot_ready.py
COPY --chown=user royells_v21_micro_workers.py ./royells_v21_micro_workers.py
COPY --chown=user royells_build_manifest.py ./royells_build_manifest.py
COPY --chown=user royells_production_intelligence.py ./royells_production_intelligence.py
COPY --chown=user app.py ./app.py
COPY --chown=user Dockerfile ./Dockerfile
COPY --chown=user royells_v20_core ./royells_v20_core
COPY --chown=user royells_v20_postgres ./royells_v20_postgres
COPY --chown=user royells_v20_redis ./royells_v20_redis
COPY --chown=user migrations ./migrations
RUN python royells_build_manifest.py --write --path build_manifest.json \
    && python -m compileall -q \
        royells_media_bot_ready.py \
        royells_v21_micro_workers.py \
        royells_build_manifest.py \
        royells_production_intelligence.py \
        app.py \
        royells_v20_core \
        royells_v20_postgres \
        royells_v20_redis \
    && echo "[ROYELLS DOCKER] python compile check passed"

EXPOSE 7860

CMD echo "[ROYELLS DOCKER] command reached; starting app.py" \
    && python -u app.py
