FROM python:3.11-slim

SHELL ["/bin/sh", "-c"]

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONFAULTHANDLER=1 \
    ROYELLS_HUGGINGFACE_SPACE=0 \
    ROYELLS_E2_MICRO_PROFILE=1 \
    ROYELLS_DATA_DIR=/data/royells_media_bot \
    ROYELLS_RUNTIME_DIR=/data/royells_media_bot/runtime \
    ROYELLS_KEEPALIVE_HTTP=0 \
    ROYELLS_TRY_COPY_MESSAGE=1 \
    ROYELLS_PRESERVE_ALBUMS=1 \
    ROYELLS_TRY_COPY_ALBUM_ITEMS=0 \
    ROYELLS_SOURCE_ALBUM_INDIVIDUAL_FALLBACK=1 \
    ROYELLS_SOURCE_ALBUM_GROUP_FAILURE_INDIVIDUAL_FALLBACK=1 \
    ROYELLS_SOURCE_ALBUM_SEND_ATTEMPTS=2 \
    ROYELLS_ZERO_BYTE_ITEM_MAX_RETRIES=3 \
    ROYELLS_SOURCE_FAST_COPY=1 \
    ROYELLS_CONTENT_FILTER_ENABLED=0 \
    ROYELLS_ALLOW_AGGRESSIVE_MAIN_WORKERS=0 \
    ROYELLS_DOWNLOAD_WORKERS=1 \
    ROYELLS_UPLOAD_WORKERS=1 \
    ROYELLS_LINK_WORKERS=1 \
    ROYELLS_BUTTON_WORKERS=2 \
    ROYELLS_TELEGRAM_API_CONCURRENCY=1 \
    ROYELLS_MAX_CONCURRENT_TRANSMISSIONS=1 \
    ROYELLS_MAIN_LOCAL_QUEUE_SOFT_LIMIT=16 \
    ROYELLS_MAIN_LOCAL_QUEUE_HARD_LIMIT=24 \
    ROYELLS_DOWNLOAD_QUEUE_LIMIT=24 \
    ROYELLS_UPLOAD_QUEUE_LIMIT=4 \
    ROYELLS_LINK_QUEUE_LIMIT=100 \
    ROYELLS_BUTTON_QUEUE_LIMIT=200 \
    ROYELLS_RETRY_QUEUE_LIMIT=5000 \
    ROYELLS_QUEUE_ADMISSION_MAX_WAIT_SECONDS=20 \
    ROYELLS_QUEUE_RECOVERY_BATCH_LIMIT=50 \
    ROYELLS_QUEUE_RECOVERY_PRESSURE_TARGET=16 \
    ROYELLS_QUEUE_RECOVERY_ITEM_DELAY_SECONDS=0.1 \
    ROYELLS_QUEUE_RECOVERY_RETRY_SECONDS=3 \
    ROYELLS_COPY_MESSAGE_ITEM_DELAY=0.05 \
    ROYELLS_ADAPTIVE_INTAKE=1 \
    ROYELLS_ADAPTIVE_INTAKE_START_DELAY_SECONDS=45 \
    ROYELLS_ADAPTIVE_INTAKE_INTERVAL_SECONDS=120 \
    ROYELLS_ADAPTIVE_INTAKE_TIMEOUT_SECONDS=900 \
    ROYELLS_STARTUP_HOT_SCAN_LIMIT=10 \
    ROYELLS_STARTUP_HOT_SCAN_HISTORY_LIMIT=50 \
    ROYELLS_HISTORICAL_BACKFILL=0 \
    ROYELLS_HISTORICAL_BACKFILL_BATCH_IDS=100 \
    ROYELLS_HISTORICAL_BACKFILL_PRESSURE_TARGET=100 \
    ROYELLS_SCAN_PREFETCH_PRESSURE_TARGET=16 \
    ROYELLS_HISTORICAL_BACKFILL_PAUSE_SECONDS=5 \
    ROYELLS_IMMEDIATE_RESCUE_ENABLED=0 \
    ROYELLS_STARTUP_CATCHUP=0 \
    ROYELLS_AUTO_SYNC=0 \
    ROYELLS_SOURCE_GUARD=0 \
    ROYELLS_AUTO_RECOVERY=0 \
    ROYELLS_LIVE_DASHBOARD=0 \
    ROYELLS_LIVE_DASHBOARD_INTERVAL_SECONDS=300 \
    ROYELLS_ASYNC_DIAGNOSTICS=0 \
    ROYELLS_CRITICAL_DB_WRITE_QUEUE_LIMIT=5000 \
    ROYELLS_JOB_STATE_DB_QUEUE_LIMIT=5000 \
    ROYELLS_DB_WRITE_BATCH_SIZE=100 \
    ROYELLS_DB_EXECUTOR_WORKERS=1 \
    ROYELLS_PERSISTENCE_EXECUTOR_WORKERS=2 \
    ROYELLS_MEDIA_EXECUTOR_WORKERS=2 \
    ROYELLS_CONTROL_EXECUTOR_WORKERS=2 \
    ROYELLS_CPU_EXECUTOR_WORKERS=1 \
    ROYELLS_TELEGRAM_CONTROL_CONCURRENCY=4 \
    ROYELLS_SOURCE_JOB_MAX_RETRIES=5 \
    ROYELLS_SOURCE_PERMANENT_RETRY=0 \
    ROYELLS_SOURCE_FAILED_RETRY_DELAY_SECONDS=600 \
    ROYELLS_STARTUP_CATCHUP_DELAY_SECONDS=120 \
    ROYELLS_AUTO_SYNC_CHANNELS_PER_RUN=4 \
    ROYELLS_AUTO_SYNC_HEALTH_CHECK=0 \
    ROYELLS_SOURCE_GUARD_LOOKBACK=20 \
    ROYELLS_SOURCE_GUARD_CATCHUP_LIMIT=500 \
    ROYELLS_SOURCE_GUARD_CHANNEL_TIMEOUT_SECONDS=120 \
    ROYELLS_SOURCE_GUARD_ACCESS_BACKOFF_SECONDS=3600 \
    ROYELLS_TARGET_MEDIA_INDEX=1 \
    ROYELLS_TARGET_MEDIA_INDEX_START_DELAY_SECONDS=7200 \
    ROYELLS_TARGET_MEDIA_INDEX_INTERVAL_SECONDS=86400 \
    ROYELLS_TARGET_MEDIA_INDEX_DELETE_DUPLICATES=1 \
    ROYELLS_TARGET_DOCUMENT_CLEANUP=1 \
    ROYELLS_TARGET_DOCUMENT_CLEANUP_START_DELAY_SECONDS=45 \
    ROYELLS_TARGET_DOCUMENT_CLEANUP_INTERVAL_SECONDS=1800 \
    ROYELLS_TARGET_DOCUMENT_CLEANUP_MAX_HISTORY=0 \
    ROYELLS_FORCE_SOURCE_VIDEO_FIX=0 \
    ROYELLS_VIDEO_FIX_PRESET=ultrafast \
    ROYELLS_VIDEO_FIX_CRF=20 \
    ROYELLS_FFMPEG_THREADS=1 \
    ROYELLS_FFMPEG_CONVERSION_TIMEOUT_SECONDS=1800 \
    ROYELLS_PROCESSING_CACHE_TTL_SECONDS=86400 \
    ROYELLS_LOG_MAX_MB=20 \
    ROYELLS_LOG_BACKUP_COUNT=5 \
    ROYELLS_DB_JOURNAL_MODE=WAL \
    ROYELLS_DB_SYNCHRONOUS=NORMAL \
    ROYELLS_SOURCE_UPLOAD_AS_DOCUMENT=0 \
    ROYELLS_SOURCE_VIDEO_UPLOAD_AS_DOCUMENT=0 \
    ROYELLS_SOURCE_PHOTO_UPLOAD_AS_DOCUMENT=0 \
    ROYELLS_SOURCE_PEER_RESOLVE_COOLDOWN_SECONDS=300 \
    ROYELLS_RUNTIME_CHECKPOINT=1 \
    ROYELLS_RUNTIME_CHECKPOINT_INTERVAL_SECONDS=15 \
    ROYELLS_RUNTIME_CHECKPOINT_CONFIRM_HISTORY_LIMIT=1000 \
    ROYELLS_RUNTIME_CHECKPOINT_MAX_AGE_DAYS=30 \
    ROYELLS_DB_RECOVERY_ARTIFACT_KEEP=3 \
    ROYELLS_HARD_WATCHDOG=1 \
    ROYELLS_HARD_WATCHDOG_FORCE_RESTART=0 \
    ROYELLS_WORKER_STALL_FORCE_RESTART=0 \
    ROYELLS_MEMORY_RESTART_LIMIT_MB=0 \
    ROYELLS_AUTO_RESTART_MAX_PER_WINDOW=0 \
    ROYELLS_AUTO_RESTART_WINDOW_SECONDS=21600 \
    ROYELLS_MAX_BULK_SOURCE_CHANNELS=100 \
    ROYELLS_BULK_SOURCE_RESOLVE_TIMEOUT_SECONDS=45 \
    ROYELLS_SLOW_DB_SECONDS=0.5 \
    ROYELLS_SLOW_API_SECONDS=5 \
    ROYELLS_SLOW_MEDIA_SECONDS=15 \
    ROYELLS_EVENT_LOOP_LAG_LOG_SECONDS=1 \
    ROYELLS_RESTORE_MAX_MEMBERS=500 \
    ROYELLS_RESTORE_MAX_UNCOMPRESSED_MB=2048 \
    ROYELLS_POST_DELAY=1

RUN apt-get update \
    && apt-get install -y --no-install-recommends ffmpeg ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m -u 1000 user \
    && mkdir -p /data \
    && chmod 777 /data

USER user
ENV HOME=/home/user \
    PATH=/home/user/.local/bin:$PATH

WORKDIR $HOME/app

COPY --chown=user requirements.txt ./requirements.txt
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

COPY --chown=user royells_media_bot_ready.py ./royells_media_bot_ready.py
COPY --chown=user app.py ./app.py
RUN python -m py_compile royells_media_bot_ready.py app.py \
    && echo "[ROYELLS DOCKER] python compile check passed"

EXPOSE 7860

CMD echo "[ROYELLS DOCKER] command reached; starting app.py" \
    && python -u app.py
