-- Royells v20 PostgreSQL schema
-- Target: PostgreSQL 16-18
-- This file contains tables, constraints, partitions, and comments.
-- Non-constraint indexes are defined in indexes.sql.

BEGIN;

CREATE SCHEMA IF NOT EXISTS royells;
SET LOCAL search_path = royells, public;
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '0';

CREATE TABLE IF NOT EXISTS schema_migrations (
    version             bigint PRIMARY KEY,
    description         text NOT NULL CHECK (btrim(description) <> ''),
    checksum_sha256     char(64) NOT NULL
                        CHECK (checksum_sha256 ~ '^[0-9a-f]{64}$'),
    applied_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    applied_by          text NOT NULL DEFAULT current_user
                        CHECK (btrim(applied_by) <> '')
);

CREATE TABLE IF NOT EXISTS migration_runs (
    migration_run_id    text PRIMARY KEY CHECK (btrim(migration_run_id) <> ''),
    source_version      text NOT NULL CHECK (btrim(source_version) <> ''),
    target_version      bigint NOT NULL,
    status              text NOT NULL
                        CHECK (status IN (
                            'planned', 'running', 'validating', 'succeeded',
                            'failed', 'rolled_back'
                        )),
    snapshot_started_at timestamptz,
    snapshot_finished_at timestamptz,
    started_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    finished_at         timestamptz,
    source_manifest     jsonb NOT NULL DEFAULT '{}'::jsonb
                        CHECK (jsonb_typeof(source_manifest) = 'object'),
    imported_counts     jsonb NOT NULL DEFAULT '{}'::jsonb
                        CHECK (jsonb_typeof(imported_counts) = 'object'),
    reconciliation      jsonb NOT NULL DEFAULT '{}'::jsonb
                        CHECK (jsonb_typeof(reconciliation) = 'object'),
    last_error          text NOT NULL DEFAULT '',
    CHECK (
        (status IN ('succeeded', 'failed', 'rolled_back') AND finished_at IS NOT NULL)
        OR
        (status NOT IN ('succeeded', 'failed', 'rolled_back'))
    )
);

CREATE TABLE IF NOT EXISTS bot_instances (
    instance_id         text PRIMARY KEY CHECK (btrim(instance_id) <> ''),
    boot_id             text NOT NULL UNIQUE CHECK (btrim(boot_id) <> ''),
    app_version         text NOT NULL CHECK (btrim(app_version) <> ''),
    deployment_id       text NOT NULL DEFAULT '',
    host_name           text NOT NULL DEFAULT '',
    process_id          integer CHECK (process_id IS NULL OR process_id > 0),
    status              text NOT NULL
                        CHECK (status IN (
                            'starting', 'recovering', 'running', 'draining',
                            'stopped', 'crashed', 'superseded'
                        )),
    started_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    ready_at            timestamptz,
    heartbeat_at        timestamptz NOT NULL DEFAULT clock_timestamp(),
    shutdown_requested_at timestamptz,
    stopped_at          timestamptz,
    shutdown_reason     text NOT NULL DEFAULT '',
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb
                        CHECK (jsonb_typeof(metadata) = 'object'),
    CHECK (ready_at IS NULL OR ready_at >= started_at),
    CHECK (stopped_at IS NULL OR stopped_at >= started_at)
);

CREATE TABLE IF NOT EXISTS runtime_config (
    config_key          text PRIMARY KEY CHECK (btrim(config_key) <> ''),
    config_value        jsonb NOT NULL,
    value_type          text NOT NULL DEFAULT 'json'
                        CHECK (value_type IN (
                            'json', 'integer', 'number', 'boolean',
                            'string', 'duration'
                        )),
    config_version      bigint NOT NULL DEFAULT 1 CHECK (config_version > 0),
    is_secret           boolean NOT NULL DEFAULT false,
    updated_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_by          text NOT NULL DEFAULT 'migration'
                        CHECK (btrim(updated_by) <> ''),
    CHECK (is_secret = false)
);

CREATE TABLE IF NOT EXISTS redis_outbox (
    outbox_id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type          text NOT NULL CHECK (btrim(event_type) <> ''),
    aggregate_type      text NOT NULL CHECK (btrim(aggregate_type) <> ''),
    aggregate_id        text NOT NULL CHECK (btrim(aggregate_id) <> ''),
    aggregate_version   bigint NOT NULL CHECK (aggregate_version >= 0),
    destination         text NOT NULL
                        CHECK (destination IN (
                            'download_queue', 'upload_queue', 'link_queue',
                            'reconciliation_queue', 'retry_queue',
                            'album_queue', 'runtime', 'config'
                        )),
    outbox_status       text NOT NULL DEFAULT 'pending'
                        CHECK (outbox_status IN (
                            'pending', 'publishing', 'published', 'dead'
                        )),
    payload             jsonb NOT NULL DEFAULT '{}'::jsonb
                        CHECK (jsonb_typeof(payload) = 'object'),
    available_at        timestamptz NOT NULL DEFAULT clock_timestamp(),
    attempt_count       integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    lease_owner_instance_id text REFERENCES bot_instances(instance_id)
                        ON DELETE RESTRICT,
    lease_token         text,
    lease_expires_at    timestamptz,
    published_at        timestamptz,
    created_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    last_error          text NOT NULL DEFAULT '',
    UNIQUE (
        event_type,
        aggregate_type,
        aggregate_id,
        aggregate_version,
        destination
    ),
    CHECK (
        (
            outbox_status = 'publishing'
            AND lease_owner_instance_id IS NOT NULL
            AND lease_token IS NOT NULL
            AND btrim(lease_token) <> ''
            AND lease_expires_at IS NOT NULL
        )
        OR
        (
            outbox_status <> 'publishing'
            AND lease_owner_instance_id IS NULL
            AND lease_token IS NULL
            AND lease_expires_at IS NULL
        )
    ),
    CHECK (
        (outbox_status = 'published' AND published_at IS NOT NULL)
        OR
        (outbox_status <> 'published' AND published_at IS NULL)
    )
);

CREATE TABLE IF NOT EXISTS source_channels (
    source_chat_id      bigint PRIMARY KEY CHECK (source_chat_id <> 0),
    title               text NOT NULL DEFAULT '',
    username            text,
    source_link         text NOT NULL DEFAULT '',
    status              text NOT NULL DEFAULT 'active'
                        CHECK (status IN (
                            'active', 'paused', 'unreachable', 'left',
                            'removed', 'ignored_system'
                        )),
    enabled             boolean NOT NULL DEFAULT true,
    priority            smallint NOT NULL DEFAULT 0
                        CHECK (priority BETWEEN -1000 AND 1000),
    added_at            timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    last_resolved_at    timestamptz,
    last_error          text NOT NULL DEFAULT '',
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb
                        CHECK (jsonb_typeof(metadata) = 'object'),
    CHECK (username IS NULL OR btrim(username) <> '')
);

CREATE TABLE IF NOT EXISTS source_identifiers (
    source_identifier_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_chat_id      bigint NOT NULL
                        REFERENCES source_channels(source_chat_id)
                        ON DELETE CASCADE,
    identifier_type     text NOT NULL
                        CHECK (identifier_type IN (
                            'chat_id', 'username', 'invite_link', 'public_link'
                        )),
    identifier_value    text NOT NULL CHECK (btrim(identifier_value) <> ''),
    normalized_value    text NOT NULL CHECK (btrim(normalized_value) <> ''),
    is_primary          boolean NOT NULL DEFAULT false,
    is_active           boolean NOT NULL DEFAULT true,
    first_seen_at       timestamptz NOT NULL DEFAULT clock_timestamp(),
    last_seen_at        timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (identifier_type, normalized_value)
);

CREATE TABLE IF NOT EXISTS source_scan_cursors (
    source_chat_id      bigint NOT NULL
                        REFERENCES source_channels(source_chat_id)
                        ON DELETE CASCADE,
    cursor_kind         text NOT NULL
                        CHECK (cursor_kind IN (
                            'hot', 'historical', 'adaptive', 'source_guard',
                            'auto_sync', 'target_index'
                        )),
    next_message_id     bigint CHECK (next_message_id IS NULL OR next_message_id > 0),
    last_scanned_message_id bigint
                        CHECK (last_scanned_message_id IS NULL OR last_scanned_message_id > 0),
    high_watermark_message_id bigint
                        CHECK (high_watermark_message_id IS NULL OR high_watermark_message_id > 0),
    completed           boolean NOT NULL DEFAULT false,
    cursor_version      bigint NOT NULL DEFAULT 1 CHECK (cursor_version > 0),
    cursor_payload      jsonb NOT NULL DEFAULT '{}'::jsonb
                        CHECK (jsonb_typeof(cursor_payload) = 'object'),
    last_success_at     timestamptz,
    last_attempt_at     timestamptz,
    last_error          text NOT NULL DEFAULT '',
    updated_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (source_chat_id, cursor_kind)
);

CREATE TABLE IF NOT EXISTS scan_runs (
    scan_run_id         text PRIMARY KEY CHECK (btrim(scan_run_id) <> ''),
    scan_type           text NOT NULL
                        CHECK (scan_type IN (
                            'hot', 'historical', 'adaptive', 'source_guard',
                            'auto_sync', 'target_index', 'manual'
                        )),
    status              text NOT NULL
                        CHECK (status IN (
                            'planned', 'running', 'paused', 'completed',
                            'failed', 'cancelled'
                        )),
    owner_instance_id   text REFERENCES bot_instances(instance_id)
                        ON DELETE SET NULL,
    started_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    heartbeat_at        timestamptz,
    completed_at        timestamptz,
    admitted_jobs       bigint NOT NULL DEFAULT 0 CHECK (admitted_jobs >= 0),
    scanned_messages    bigint NOT NULL DEFAULT 0 CHECK (scanned_messages >= 0),
    config_snapshot     jsonb NOT NULL DEFAULT '{}'::jsonb
                        CHECK (jsonb_typeof(config_snapshot) = 'object'),
    last_error          text NOT NULL DEFAULT '',
    CHECK (
        (status IN ('completed', 'failed', 'cancelled') AND completed_at IS NOT NULL)
        OR
        (status NOT IN ('completed', 'failed', 'cancelled'))
    )
);

CREATE TABLE IF NOT EXISTS scan_run_sources (
    scan_run_id         text NOT NULL
                        REFERENCES scan_runs(scan_run_id)
                        ON DELETE CASCADE,
    source_chat_id      bigint NOT NULL
                        REFERENCES source_channels(source_chat_id)
                        ON DELETE RESTRICT,
    status              text NOT NULL
                        CHECK (status IN (
                            'pending', 'running', 'paused', 'completed',
                            'failed', 'skipped'
                        )),
    cursor_before       jsonb NOT NULL DEFAULT '{}'::jsonb
                        CHECK (jsonb_typeof(cursor_before) = 'object'),
    cursor_after        jsonb NOT NULL DEFAULT '{}'::jsonb
                        CHECK (jsonb_typeof(cursor_after) = 'object'),
    scanned_messages    bigint NOT NULL DEFAULT 0 CHECK (scanned_messages >= 0),
    admitted_jobs       bigint NOT NULL DEFAULT 0 CHECK (admitted_jobs >= 0),
    retry_count         integer NOT NULL DEFAULT 0 CHECK (retry_count >= 0),
    started_at          timestamptz,
    completed_at        timestamptz,
    last_error          text NOT NULL DEFAULT '',
    updated_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (scan_run_id, source_chat_id)
);

CREATE TABLE IF NOT EXISTS subscriptions (
    user_id             bigint PRIMARY KEY CHECK (user_id > 0),
    status              text NOT NULL DEFAULT 'active'
                        CHECK (status IN (
                            'active', 'expired', 'banned', 'removed'
                        )),
    expire_at           timestamptz,
    first_name          text NOT NULL DEFAULT '',
    last_name           text NOT NULL DEFAULT '',
    username            text,
    profile_updated_at  timestamptz,
    created_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb
                        CHECK (jsonb_typeof(metadata) = 'object'),
    CHECK (username IS NULL OR btrim(username) <> '')
);

CREATE TABLE IF NOT EXISTS media_objects (
    media_uid           text PRIMARY KEY CHECK (btrim(media_uid) <> ''),
    media_type          text NOT NULL DEFAULT 'unknown'
                        CHECK (media_type IN (
                            'photo', 'video', 'document', 'audio', 'voice',
                            'animation', 'video_note', 'sticker', 'unknown'
                        )),
    telegram_file_unique_id text,
    mime_type           text,
    file_size_bytes     bigint CHECK (file_size_bytes IS NULL OR file_size_bytes >= 0),
    width               integer CHECK (width IS NULL OR width > 0),
    height              integer CHECK (height IS NULL OR height > 0),
    duration_seconds    integer CHECK (duration_seconds IS NULL OR duration_seconds >= 0),
    content_sha256      char(64)
                        CHECK (content_sha256 IS NULL OR content_sha256 ~ '^[0-9a-f]{64}$'),
    first_seen_at       timestamptz NOT NULL DEFAULT clock_timestamp(),
    last_seen_at        timestamptz NOT NULL DEFAULT clock_timestamp(),
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb
                        CHECK (jsonb_typeof(metadata) = 'object'),
    CHECK (
        telegram_file_unique_id IS NULL
        OR btrim(telegram_file_unique_id) <> ''
    )
);

CREATE TABLE IF NOT EXISTS media_groups (
    source_chat_id      bigint NOT NULL
                        REFERENCES source_channels(source_chat_id)
                        ON DELETE RESTRICT,
    media_group_id      text NOT NULL CHECK (btrim(media_group_id) <> ''),
    assembly_status     text NOT NULL DEFAULT 'assembling'
                        CHECK (assembly_status IN (
                            'assembling', 'ready', 'expired', 'admitted',
                            'completed', 'failed'
                        )),
    expected_item_count smallint
                        CHECK (expected_item_count IS NULL OR expected_item_count > 0),
    actual_item_count   smallint NOT NULL DEFAULT 0 CHECK (actual_item_count >= 0),
    first_message_id    bigint CHECK (first_message_id IS NULL OR first_message_id > 0),
    last_message_id     bigint CHECK (last_message_id IS NULL OR last_message_id > 0),
    flush_after         timestamptz,
    created_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    completed_at        timestamptz,
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb
                        CHECK (jsonb_typeof(metadata) = 'object'),
    PRIMARY KEY (source_chat_id, media_group_id),
    CHECK (
        expected_item_count IS NULL
        OR actual_item_count <= expected_item_count
    )
);

CREATE TABLE IF NOT EXISTS source_messages (
    source_chat_id      bigint NOT NULL
                        REFERENCES source_channels(source_chat_id)
                        ON DELETE RESTRICT,
    source_message_id   bigint NOT NULL CHECK (source_message_id > 0),
    media_uid           text REFERENCES media_objects(media_uid)
                        ON DELETE RESTRICT,
    media_group_id      text,
    media_type          text NOT NULL DEFAULT 'unknown'
                        CHECK (media_type IN (
                            'photo', 'video', 'document', 'audio', 'voice',
                            'animation', 'video_note', 'sticker', 'unknown'
                        )),
    sent_at             timestamptz,
    caption             text NOT NULL DEFAULT '',
    is_protected        boolean NOT NULL DEFAULT false,
    first_seen_at       timestamptz NOT NULL DEFAULT clock_timestamp(),
    last_seen_at        timestamptz NOT NULL DEFAULT clock_timestamp(),
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb
                        CHECK (jsonb_typeof(metadata) = 'object'),
    PRIMARY KEY (source_chat_id, source_message_id),
    FOREIGN KEY (source_chat_id, media_group_id)
        REFERENCES media_groups(source_chat_id, media_group_id)
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS media_group_items (
    source_chat_id      bigint NOT NULL,
    media_group_id      text NOT NULL,
    item_position       smallint NOT NULL CHECK (item_position > 0),
    source_message_id   bigint NOT NULL CHECK (source_message_id > 0),
    media_uid           text REFERENCES media_objects(media_uid)
                        ON DELETE RESTRICT,
    created_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (source_chat_id, media_group_id, item_position),
    UNIQUE (source_chat_id, source_message_id),
    FOREIGN KEY (source_chat_id, media_group_id)
        REFERENCES media_groups(source_chat_id, media_group_id)
        ON DELETE CASCADE,
    FOREIGN KEY (source_chat_id, source_message_id)
        REFERENCES source_messages(source_chat_id, source_message_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS worker_instances (
    worker_id           text PRIMARY KEY CHECK (btrim(worker_id) <> ''),
    instance_id         text NOT NULL
                        REFERENCES bot_instances(instance_id)
                        ON DELETE RESTRICT,
    worker_type         text NOT NULL
                        CHECK (worker_type IN (
                            'download', 'upload', 'link', 'button',
                            'retry', 'album', 'cleanup', 'db_writer',
                            'db_critical', 'db_job_state', 'scanner',
                            'reconciler', 'queue_healer', 'gateway'
                        )),
    ordinal             smallint NOT NULL CHECK (ordinal >= 0),
    status              text NOT NULL
                        CHECK (status IN (
                            'starting', 'idle', 'working', 'waiting',
                            'stopping', 'stopped', 'failed'
                        )),
    started_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    heartbeat_at        timestamptz NOT NULL DEFAULT clock_timestamp(),
    stopped_at          timestamptz,
    last_error          text NOT NULL DEFAULT '',
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb
                        CHECK (jsonb_typeof(metadata) = 'object'),
    UNIQUE (instance_id, worker_type, ordinal)
);

CREATE TABLE IF NOT EXISTS media_jobs (
    job_id              text PRIMARY KEY CHECK (btrim(job_id) <> ''),
    post_uid            text NOT NULL DEFAULT '',
    job_type            text NOT NULL
                        CHECK (job_type IN (
                            'single', 'album', 'link', 'reconciliation',
                            'target_index'
                        )),
    source_kind         text NOT NULL DEFAULT 'source'
                        CHECK (source_kind IN (
                            'source', 'realtime', 'hot', 'historical',
                            'adaptive', 'manual_link', 'recovery',
                            'target_scan'
                        )),
    source_chat_id      bigint REFERENCES source_channels(source_chat_id)
                        ON DELETE RESTRICT,
    source_name         text NOT NULL DEFAULT '',
    scan_run_id         text REFERENCES scan_runs(scan_run_id)
                        ON DELETE SET NULL,
    status              text NOT NULL
                        CHECK (status IN (
                            'admitted', 'queued', 'downloading', 'downloaded',
                            'uploading', 'reconciling', 'retry_wait',
                            'completed', 'failed', 'dead', 'cancelled'
                        )),
    current_stage       text NOT NULL DEFAULT '',
    priority            smallint NOT NULL DEFAULT 0
                        CHECK (priority BETWEEN -1000 AND 1000),
    attempt_count       integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    max_attempts        integer NOT NULL DEFAULT 12 CHECK (max_attempts > 0),
    not_before          timestamptz NOT NULL DEFAULT clock_timestamp(),
    last_error_code     text NOT NULL DEFAULT '',
    last_error          text NOT NULL DEFAULT '',
    created_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    completed_at        timestamptz,
    row_version         bigint NOT NULL DEFAULT 1 CHECK (row_version > 0),
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb
                        CHECK (jsonb_typeof(metadata) = 'object'),
    CHECK (
        (status IN ('completed', 'failed', 'dead', 'cancelled') AND completed_at IS NOT NULL)
        OR
        (status NOT IN ('completed', 'failed', 'dead', 'cancelled') AND completed_at IS NULL)
    )
);

CREATE TABLE IF NOT EXISTS job_items (
    job_id              text NOT NULL
                        REFERENCES media_jobs(job_id)
                        ON DELETE CASCADE,
    item_no             smallint NOT NULL CHECK (item_no > 0),
    source_chat_id      bigint NOT NULL,
    source_message_id   bigint NOT NULL CHECK (source_message_id > 0),
    media_uid           text REFERENCES media_objects(media_uid)
                        ON DELETE RESTRICT,
    item_status         text NOT NULL DEFAULT 'pending'
                        CHECK (item_status IN (
                            'pending', 'downloading', 'downloaded', 'uploading',
                            'accepted', 'committed', 'failed', 'dead', 'skipped'
                        )),
    target_message_id   bigint CHECK (target_message_id IS NULL OR target_message_id > 0),
    last_error          text NOT NULL DEFAULT '',
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb
                        CHECK (jsonb_typeof(metadata) = 'object'),
    PRIMARY KEY (job_id, item_no),
    UNIQUE (job_id, source_chat_id, source_message_id),
    FOREIGN KEY (source_chat_id, source_message_id)
        REFERENCES source_messages(source_chat_id, source_message_id)
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS job_files (
    job_file_id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id              text NOT NULL
                        REFERENCES media_jobs(job_id)
                        ON DELETE CASCADE,
    item_no             smallint,
    file_role           text NOT NULL
                        CHECK (file_role IN (
                            'download', 'partial', 'prepared', 'thumbnail',
                            'temporary'
                        )),
    file_state          text NOT NULL
                        CHECK (file_state IN (
                            'expected', 'downloading', 'complete', 'validating',
                            'ready', 'uploading', 'consumed', 'orphaned',
                            'deleted', 'invalid'
                        )),
    storage_key         text NOT NULL CHECK (
                            btrim(storage_key) <> ''
                            AND storage_key !~ '(^/|(^|/)\.\.(/|$))'
                        ),
    expected_size_bytes bigint CHECK (expected_size_bytes IS NULL OR expected_size_bytes >= 0),
    actual_size_bytes   bigint CHECK (actual_size_bytes IS NULL OR actual_size_bytes >= 0),
    bytes_completed     bigint NOT NULL DEFAULT 0 CHECK (bytes_completed >= 0),
    checksum_sha256     char(64)
                        CHECK (checksum_sha256 IS NULL OR checksum_sha256 ~ '^[0-9a-f]{64}$'),
    modified_at         timestamptz,
    cleanup_after       timestamptz,
    created_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb
                        CHECK (jsonb_typeof(metadata) = 'object'),
    UNIQUE (job_id, storage_key),
    FOREIGN KEY (job_id, item_no)
        REFERENCES job_items(job_id, item_no)
        ON DELETE CASCADE,
    CHECK (
        expected_size_bytes IS NULL
        OR bytes_completed <= expected_size_bytes
    )
);

CREATE TABLE IF NOT EXISTS job_transfer_state (
    transfer_id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id              text NOT NULL,
    item_no             smallint NOT NULL CHECK (item_no > 0),
    direction           text NOT NULL CHECK (direction IN ('download', 'upload')),
    transfer_status     text NOT NULL
                        CHECK (transfer_status IN (
                            'pending', 'running', 'paused', 'complete',
                            'ambiguous', 'failed', 'cancelled'
                        )),
    bytes_total         bigint CHECK (bytes_total IS NULL OR bytes_total >= 0),
    bytes_transferred   bigint NOT NULL DEFAULT 0 CHECK (bytes_transferred >= 0),
    retry_count         integer NOT NULL DEFAULT 0 CHECK (retry_count >= 0),
    telegram_request_id text,
    resume_token        jsonb NOT NULL DEFAULT '{}'::jsonb
                        CHECK (jsonb_typeof(resume_token) = 'object'),
    last_error          text NOT NULL DEFAULT '',
    started_at          timestamptz,
    updated_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    completed_at        timestamptz,
    UNIQUE (job_id, item_no, direction),
    FOREIGN KEY (job_id, item_no)
        REFERENCES job_items(job_id, item_no)
        ON DELETE CASCADE,
    CHECK (bytes_total IS NULL OR bytes_transferred <= bytes_total)
);

CREATE SEQUENCE IF NOT EXISTS job_queue_order_seq AS bigint;

CREATE TABLE IF NOT EXISTS queue_runtime_state (
    queue_name          text PRIMARY KEY
                        CHECK (queue_name IN (
                            'download', 'upload', 'link', 'retry', 'admission',
                            'album', 'processing', 'reconciliation',
                            'db_critical', 'db_job_state'
                        )),
    global_virtual_time numeric(24, 6) NOT NULL DEFAULT 0
                        CHECK (global_virtual_time >= 0),
    lane_cursor         integer NOT NULL DEFAULT 0 CHECK (lane_cursor >= 0),
    lane_epoch          bigint NOT NULL DEFAULT 0 CHECK (lane_epoch >= 0),
    row_version         bigint NOT NULL DEFAULT 1 CHECK (row_version > 0),
    updated_at          timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE IF NOT EXISTS queue_fairness_state (
    queue_name          text NOT NULL
                        REFERENCES queue_runtime_state(queue_name)
                        ON DELETE CASCADE,
    priority_class      text NOT NULL
                        CHECK (priority_class IN (
                            'critical', 'interactive', 'realtime',
                            'hot', 'historical', 'maintenance'
                        )),
    fairness_key        text NOT NULL CHECK (btrim(fairness_key) <> ''),
    source_weight       numeric(18, 6) NOT NULL DEFAULT 1
                        CHECK (source_weight > 0),
    last_virtual_finish numeric(24, 6) NOT NULL DEFAULT 0
                        CHECK (last_virtual_finish >= 0),
    last_served_at      timestamptz,
    admitted_count      bigint NOT NULL DEFAULT 0 CHECK (admitted_count >= 0),
    completed_count     bigint NOT NULL DEFAULT 0 CHECK (completed_count >= 0),
    row_version         bigint NOT NULL DEFAULT 1 CHECK (row_version > 0),
    updated_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (queue_name, priority_class, fairness_key),
    CHECK (completed_count <= admitted_count)
);

CREATE TABLE IF NOT EXISTS job_queue_entries (
    queue_entry_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id              text NOT NULL
                        REFERENCES media_jobs(job_id)
                        ON DELETE CASCADE,
    queue_name          text NOT NULL
                        CHECK (queue_name IN (
                            'download', 'upload', 'link', 'retry', 'admission',
                            'album', 'processing', 'reconciliation',
                            'db_critical', 'db_job_state'
                        )),
    next_queue_name     text
                        CHECK (
                            next_queue_name IS NULL
                            OR next_queue_name IN (
                                'download', 'upload', 'link', 'admission',
                                'album', 'reconciliation'
                            )
                        ),
    state               text NOT NULL
                        CHECK (state IN (
                            'ready', 'delayed', 'leased', 'done',
                            'cancelled', 'dead'
                        )),
    priority            smallint NOT NULL DEFAULT 0
                        CHECK (priority BETWEEN -1000 AND 1000),
    priority_class      text NOT NULL DEFAULT 'historical'
                        CHECK (priority_class IN (
                            'critical', 'interactive', 'realtime',
                            'hot', 'historical', 'maintenance'
                        )),
    fairness_key        text NOT NULL DEFAULT 'global'
                        CHECK (btrim(fairness_key) <> ''),
    estimated_cost      numeric(18, 6) NOT NULL DEFAULT 1
                        CHECK (estimated_cost > 0),
    virtual_start       numeric(24, 6) NOT NULL DEFAULT 0
                        CHECK (virtual_start >= 0),
    virtual_finish      numeric(24, 6) NOT NULL DEFAULT 0
                        CHECK (virtual_finish >= virtual_start),
    queue_order         bigint NOT NULL DEFAULT nextval('job_queue_order_seq'),
    available_at        timestamptz NOT NULL DEFAULT clock_timestamp(),
    lease_owner_worker_id text REFERENCES worker_instances(worker_id)
                        ON DELETE RESTRICT,
    lease_token         text,
    lease_expires_at    timestamptz,
    lease_heartbeat_at  timestamptz,
    lease_failures      integer NOT NULL DEFAULT 0 CHECK (lease_failures >= 0),
    attempt_count       integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    last_error          text NOT NULL DEFAULT '',
    enqueued_at         timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    completed_at        timestamptz,
    row_version         bigint NOT NULL DEFAULT 1 CHECK (row_version > 0),
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb
                        CHECK (jsonb_typeof(metadata) = 'object'),
    UNIQUE (queue_order),
    CHECK (
        (
            state = 'leased'
            AND lease_owner_worker_id IS NOT NULL
            AND lease_token IS NOT NULL
            AND btrim(lease_token) <> ''
            AND lease_expires_at IS NOT NULL
        )
        OR
        (
            state <> 'leased'
            AND lease_owner_worker_id IS NULL
            AND lease_token IS NULL
            AND lease_expires_at IS NULL
        )
    ),
    CHECK (
        (state IN ('done', 'cancelled', 'dead') AND completed_at IS NOT NULL)
        OR
        (state NOT IN ('done', 'cancelled', 'dead') AND completed_at IS NULL)
    ),
    CHECK (
        (priority_class = 'critical' AND priority BETWEEN 900 AND 1000)
        OR
        (priority_class = 'interactive' AND priority BETWEEN 600 AND 899)
        OR
        (priority_class = 'realtime' AND priority BETWEEN 300 AND 599)
        OR
        (priority_class = 'hot' AND priority BETWEEN 100 AND 299)
        OR
        (priority_class = 'historical' AND priority BETWEEN 0 AND 99)
        OR
        (priority_class = 'maintenance' AND priority BETWEEN -1000 AND -1)
    )
);

CREATE TABLE IF NOT EXISTS processing_reservations (
    reservation_key    text PRIMARY KEY CHECK (btrim(reservation_key) <> ''),
    reservation_kind   text NOT NULL
                        CHECK (reservation_kind IN (
                            'media_uid', 'legacy_hash', 'source_message',
                            'media_group'
                        )),
    job_id              text NOT NULL
                        REFERENCES media_jobs(job_id)
                        ON DELETE CASCADE,
    media_uid           text REFERENCES media_objects(media_uid)
                        ON DELETE RESTRICT,
    source_chat_id      bigint,
    source_message_id   bigint CHECK (source_message_id IS NULL OR source_message_id > 0),
    owner_instance_id   text REFERENCES bot_instances(instance_id)
                        ON DELETE SET NULL,
    owner_worker_id     text REFERENCES worker_instances(worker_id)
                        ON DELETE SET NULL,
    fencing_token       bigint NOT NULL CHECK (fencing_token > 0),
    state               text NOT NULL
                        CHECK (state IN ('active', 'released', 'expired')),
    acquired_at         timestamptz NOT NULL DEFAULT clock_timestamp(),
    heartbeat_at        timestamptz NOT NULL DEFAULT clock_timestamp(),
    expires_at          timestamptz NOT NULL,
    released_at         timestamptz,
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb
                        CHECK (jsonb_typeof(metadata) = 'object'),
    CHECK (expires_at > acquired_at),
    CHECK (
        (state = 'active' AND released_at IS NULL)
        OR
        (state <> 'active' AND released_at IS NOT NULL)
    ),
    FOREIGN KEY (source_chat_id, source_message_id)
        REFERENCES source_messages(source_chat_id, source_message_id)
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS delivery_intents (
    delivery_intent_id  text PRIMARY KEY CHECK (btrim(delivery_intent_id) <> ''),
    job_id              text NOT NULL
                        REFERENCES media_jobs(job_id)
                        ON DELETE RESTRICT,
    operation           text NOT NULL CHECK (btrim(operation) <> ''),
    status              text NOT NULL
                        CHECK (status IN (
                            'prepared', 'submitting', 'accepted', 'ambiguous',
                            'confirmed', 'committed', 'failed', 'cancelled'
                        )),
    request_fingerprint char(64) NOT NULL UNIQUE
                        CHECK (request_fingerprint ~ '^[0-9a-f]{64}$'),
    target_chat_id      bigint NOT NULL CHECK (target_chat_id <> 0),
    expected_item_count smallint NOT NULL CHECK (expected_item_count > 0),
    attempt_no          integer NOT NULL DEFAULT 1 CHECK (attempt_no > 0),
    telegram_random_id  bigint,
    reconcile_after     timestamptz,
    submitted_at        timestamptz,
    accepted_at         timestamptz,
    confirmed_at        timestamptz,
    committed_at        timestamptz,
    last_error_code     text NOT NULL DEFAULT '',
    last_error          text NOT NULL DEFAULT '',
    created_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    row_version         bigint NOT NULL DEFAULT 1 CHECK (row_version > 0),
    request_metadata    jsonb NOT NULL DEFAULT '{}'::jsonb
                        CHECK (jsonb_typeof(request_metadata) = 'object'),
    CHECK (
        status <> 'committed'
        OR committed_at IS NOT NULL
    ),
    CHECK (
        status NOT IN ('accepted', 'confirmed', 'committed')
        OR accepted_at IS NOT NULL
    ),
    CHECK (
        status NOT IN ('confirmed', 'committed')
        OR confirmed_at IS NOT NULL
    )
);

CREATE TABLE IF NOT EXISTS delivery_intent_items (
    delivery_intent_id  text NOT NULL
                        REFERENCES delivery_intents(delivery_intent_id)
                        ON DELETE CASCADE,
    item_no             smallint NOT NULL CHECK (item_no > 0),
    source_chat_id      bigint NOT NULL,
    source_message_id   bigint NOT NULL CHECK (source_message_id > 0),
    media_uid           text REFERENCES media_objects(media_uid)
                        ON DELETE RESTRICT,
    target_chat_id      bigint NOT NULL CHECK (target_chat_id <> 0),
    target_message_id   bigint CHECK (target_message_id IS NULL OR target_message_id > 0),
    item_status         text NOT NULL DEFAULT 'pending'
                        CHECK (item_status IN (
                            'pending', 'submitted', 'accepted', 'confirmed',
                            'committed', 'failed', 'missing'
                        )),
    accepted_at         timestamptz,
    confirmed_at        timestamptz,
    response_metadata   jsonb NOT NULL DEFAULT '{}'::jsonb
                        CHECK (jsonb_typeof(response_metadata) = 'object'),
    PRIMARY KEY (delivery_intent_id, item_no),
    FOREIGN KEY (source_chat_id, source_message_id)
        REFERENCES source_messages(source_chat_id, source_message_id)
        ON DELETE RESTRICT,
    CHECK (
        item_status NOT IN ('accepted', 'confirmed', 'committed')
        OR target_message_id IS NOT NULL
    )
);

CREATE TABLE IF NOT EXISTS target_media_registry (
    media_uid           text PRIMARY KEY
                        REFERENCES media_objects(media_uid)
                        ON DELETE RESTRICT,
    target_chat_id      bigint NOT NULL CHECK (target_chat_id <> 0),
    target_message_id   bigint NOT NULL CHECK (target_message_id > 0),
    source_chat_id      bigint,
    source_message_id   bigint CHECK (source_message_id IS NULL OR source_message_id > 0),
    job_id              text REFERENCES media_jobs(job_id)
                        ON DELETE SET NULL,
    delivery_intent_id  text REFERENCES delivery_intents(delivery_intent_id)
                        ON DELETE SET NULL,
    registry_status     text NOT NULL DEFAULT 'active'
                        CHECK (registry_status IN (
                            'active', 'deleted', 'replaced', 'quarantined'
                        )),
    source              text NOT NULL DEFAULT 'migration'
                        CHECK (btrim(source) <> ''),
    indexed_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    deleted_at          timestamptz,
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb
                        CHECK (jsonb_typeof(metadata) = 'object'),
    CHECK (
        (registry_status = 'deleted' AND deleted_at IS NOT NULL)
        OR
        (registry_status <> 'deleted' AND deleted_at IS NULL)
    ),
    FOREIGN KEY (source_chat_id, source_message_id)
        REFERENCES source_messages(source_chat_id, source_message_id)
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS deduplication_keys (
    dedup_key           text PRIMARY KEY CHECK (btrim(dedup_key) <> ''),
    key_kind            text NOT NULL
                        CHECK (key_kind IN (
                            'media_uid', 'legacy_hash', 'source_message',
                            'target_message'
                        )),
    media_uid           text REFERENCES media_objects(media_uid)
                        ON DELETE RESTRICT,
    source_chat_id      bigint,
    source_message_id   bigint CHECK (source_message_id IS NULL OR source_message_id > 0),
    target_chat_id      bigint,
    target_message_id   bigint CHECK (target_message_id IS NULL OR target_message_id > 0),
    first_job_id        text REFERENCES media_jobs(job_id)
                        ON DELETE SET NULL,
    status              text NOT NULL DEFAULT 'active'
                        CHECK (status IN ('active', 'released', 'tombstoned')),
    first_seen_at       timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    released_at         timestamptz,
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb
                        CHECK (jsonb_typeof(metadata) = 'object'),
    CHECK (
        (status = 'active' AND released_at IS NULL)
        OR
        (status <> 'active' AND released_at IS NOT NULL)
    ),
    FOREIGN KEY (source_chat_id, source_message_id)
        REFERENCES source_messages(source_chat_id, source_message_id)
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS dead_media (
    media_uid           text PRIMARY KEY
                        REFERENCES media_objects(media_uid)
                        ON DELETE RESTRICT,
    status              text NOT NULL DEFAULT 'dead'
                        CHECK (status IN ('retryable', 'dead', 'cleared')),
    failure_count       integer NOT NULL DEFAULT 1 CHECK (failure_count > 0),
    reason_code         text NOT NULL DEFAULT '',
    reason              text NOT NULL DEFAULT '',
    source_chat_id      bigint,
    source_title        text NOT NULL DEFAULT '',
    first_failed_at     timestamptz NOT NULL DEFAULT clock_timestamp(),
    last_failed_at      timestamptz NOT NULL DEFAULT clock_timestamp(),
    cleared_at          timestamptz,
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb
                        CHECK (jsonb_typeof(metadata) = 'object'),
    CHECK (
        (status = 'cleared' AND cleared_at IS NOT NULL)
        OR
        (status <> 'cleared' AND cleared_at IS NULL)
    ),
    FOREIGN KEY (source_chat_id)
        REFERENCES source_channels(source_chat_id)
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS content_filter_hashes (
    content_filter_hash_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hash_value          text NOT NULL CHECK (btrim(hash_value) <> ''),
    hash_type           text NOT NULL CHECK (btrim(hash_type) <> ''),
    created_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (hash_type, hash_value)
);

CREATE TABLE IF NOT EXISTS telegram_requests (
    telegram_request_id text PRIMARY KEY CHECK (btrim(telegram_request_id) <> ''),
    idempotency_key     char(64) NOT NULL UNIQUE
                        CHECK (idempotency_key ~ '^[0-9a-f]{64}$'),
    job_id              text REFERENCES media_jobs(job_id)
                        ON DELETE SET NULL,
    delivery_intent_id  text REFERENCES delivery_intents(delivery_intent_id)
                        ON DELETE SET NULL,
    operation           text NOT NULL CHECK (btrim(operation) <> ''),
    client_role         text NOT NULL CHECK (client_role IN ('bot', 'userbot')),
    status              text NOT NULL
                        CHECK (status IN (
                            'prepared', 'inflight', 'accepted', 'ambiguous',
                            'confirmed', 'failed', 'cancelled'
                        )),
    attempt_no          integer NOT NULL DEFAULT 1 CHECK (attempt_no > 0),
    started_at          timestamptz,
    deadline_at         timestamptz,
    finished_at         timestamptz,
    next_reconcile_at   timestamptz,
    last_error_code     text NOT NULL DEFAULT '',
    last_error          text NOT NULL DEFAULT '',
    request_metadata    jsonb NOT NULL DEFAULT '{}'::jsonb
                        CHECK (jsonb_typeof(request_metadata) = 'object'),
    response_metadata   jsonb NOT NULL DEFAULT '{}'::jsonb
                        CHECK (jsonb_typeof(response_metadata) = 'object'),
    created_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at          timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE IF NOT EXISTS runtime_leases (
    lease_name          text PRIMARY KEY CHECK (btrim(lease_name) <> ''),
    lease_kind          text NOT NULL
                        CHECK (lease_kind IN (
                            'singleton_task', 'telegram_gateway',
                            'semaphore_permit', 'migration', 'maintenance'
                        )),
    owner_instance_id   text REFERENCES bot_instances(instance_id)
                        ON DELETE SET NULL,
    owner_worker_id     text REFERENCES worker_instances(worker_id)
                        ON DELETE SET NULL,
    fencing_token       bigint NOT NULL DEFAULT 1 CHECK (fencing_token > 0),
    status              text NOT NULL
                        CHECK (status IN ('free', 'held', 'expired')),
    acquired_at         timestamptz,
    heartbeat_at        timestamptz,
    expires_at          timestamptz,
    state_payload       jsonb NOT NULL DEFAULT '{}'::jsonb
                        CHECK (jsonb_typeof(state_payload) = 'object'),
    updated_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    CHECK (
        (
            status = 'held'
            AND owner_instance_id IS NOT NULL
            AND expires_at IS NOT NULL
        )
        OR
        status <> 'held'
    )
);

CREATE TABLE IF NOT EXISTS rate_limit_state (
    scope_key           text PRIMARY KEY CHECK (btrim(scope_key) <> ''),
    limiter_kind        text NOT NULL
                        CHECK (limiter_kind IN (
                            'flood_wait', 'token_bucket', 'cooldown'
                        )),
    blocked_until       timestamptz,
    tokens_available    numeric(20, 6),
    refill_rate         numeric(20, 6),
    penalty_level       integer NOT NULL DEFAULT 0 CHECK (penalty_level >= 0),
    state_version       bigint NOT NULL DEFAULT 1 CHECK (state_version > 0),
    state_payload       jsonb NOT NULL DEFAULT '{}'::jsonb
                        CHECK (jsonb_typeof(state_payload) = 'object'),
    updated_at          timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE IF NOT EXISTS runtime_checkpoints (
    checkpoint_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checkpoint_kind     text NOT NULL CHECK (btrim(checkpoint_kind) <> ''),
    schema_version      integer NOT NULL CHECK (schema_version > 0),
    app_version         text NOT NULL CHECK (btrim(app_version) <> ''),
    sequence_no         bigint NOT NULL CHECK (sequence_no > 0),
    checksum_sha256     char(64) NOT NULL
                        CHECK (checksum_sha256 ~ '^[0-9a-f]{64}$'),
    checkpoint_status   text NOT NULL DEFAULT 'current'
                        CHECK (checkpoint_status IN (
                            'current', 'superseded', 'rejected'
                        )),
    payload             jsonb NOT NULL CHECK (jsonb_typeof(payload) = 'object'),
    instance_id         text REFERENCES bot_instances(instance_id)
                        ON DELETE SET NULL,
    created_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    rejection_reason    text NOT NULL DEFAULT '',
    UNIQUE (checkpoint_kind, sequence_no)
);

CREATE TABLE IF NOT EXISTS runtime_health (
    component_key       text PRIMARY KEY CHECK (btrim(component_key) <> ''),
    instance_id         text REFERENCES bot_instances(instance_id)
                        ON DELETE SET NULL,
    health_status       text NOT NULL
                        CHECK (health_status IN (
                            'starting', 'ready', 'degraded', 'failed', 'stopped'
                        )),
    reason              text NOT NULL DEFAULT '',
    last_seen_at        timestamptz NOT NULL DEFAULT clock_timestamp(),
    details             jsonb NOT NULL DEFAULT '{}'::jsonb
                        CHECK (jsonb_typeof(details) = 'object')
);

CREATE TABLE IF NOT EXISTS migration_rejects (
    migration_reject_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    migration_run_id    text NOT NULL
                        REFERENCES migration_runs(migration_run_id)
                        ON DELETE CASCADE,
    source_name         text NOT NULL CHECK (btrim(source_name) <> ''),
    source_key          text NOT NULL DEFAULT '',
    reason_code         text NOT NULL CHECK (btrim(reason_code) <> ''),
    reason              text NOT NULL DEFAULT '',
    source_payload      jsonb NOT NULL DEFAULT '{}'::jsonb
                        CHECK (jsonb_typeof(source_payload) = 'object'),
    created_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    resolved_at         timestamptz,
    resolution          text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS job_events (
    event_at            timestamptz NOT NULL DEFAULT clock_timestamp(),
    event_id            bigint GENERATED BY DEFAULT AS IDENTITY,
    job_id              text NOT NULL,
    queue_entry_id      bigint,
    worker_id           text,
    event_type          text NOT NULL CHECK (btrim(event_type) <> ''),
    from_status         text NOT NULL DEFAULT '',
    to_status           text NOT NULL DEFAULT '',
    attempt_no          integer CHECK (attempt_no IS NULL OR attempt_no >= 0),
    severity            text NOT NULL DEFAULT 'info'
                        CHECK (severity IN ('debug', 'info', 'warning', 'error')),
    error_code          text NOT NULL DEFAULT '',
    details             jsonb NOT NULL DEFAULT '{}'::jsonb
                        CHECK (jsonb_typeof(details) = 'object'),
    PRIMARY KEY (event_at, event_id)
) PARTITION BY RANGE (event_at);

CREATE TABLE IF NOT EXISTS delivery_history (
    delivered_at        timestamptz NOT NULL DEFAULT clock_timestamp(),
    delivery_history_id bigint GENERATED BY DEFAULT AS IDENTITY,
    delivery_intent_id  text,
    job_id              text,
    media_uid           text,
    source_chat_id      bigint,
    source_message_id   bigint,
    target_chat_id      bigint NOT NULL CHECK (target_chat_id <> 0),
    target_message_id   bigint CHECK (target_message_id IS NULL OR target_message_id > 0),
    outcome             text NOT NULL
                        CHECK (outcome IN (
                            'accepted', 'confirmed', 'committed', 'ambiguous',
                            'failed', 'deleted', 'replaced'
                        )),
    operation           text NOT NULL DEFAULT '',
    details             jsonb NOT NULL DEFAULT '{}'::jsonb
                        CHECK (jsonb_typeof(details) = 'object'),
    PRIMARY KEY (delivered_at, delivery_history_id)
) PARTITION BY RANGE (delivered_at);

CREATE TABLE IF NOT EXISTS source_scan_events (
    event_at            timestamptz NOT NULL DEFAULT clock_timestamp(),
    source_scan_event_id bigint GENERATED BY DEFAULT AS IDENTITY,
    scan_run_id         text,
    source_chat_id      bigint NOT NULL CHECK (source_chat_id <> 0),
    cursor_kind         text NOT NULL DEFAULT '',
    event_type          text NOT NULL CHECK (btrim(event_type) <> ''),
    message_id_from     bigint CHECK (message_id_from IS NULL OR message_id_from > 0),
    message_id_to       bigint CHECK (message_id_to IS NULL OR message_id_to > 0),
    scanned_count       integer NOT NULL DEFAULT 0 CHECK (scanned_count >= 0),
    admitted_count      integer NOT NULL DEFAULT 0 CHECK (admitted_count >= 0),
    details             jsonb NOT NULL DEFAULT '{}'::jsonb
                        CHECK (jsonb_typeof(details) = 'object'),
    PRIMARY KEY (event_at, source_scan_event_id)
) PARTITION BY RANGE (event_at);

CREATE TABLE IF NOT EXISTS audit_events (
    event_at            timestamptz NOT NULL DEFAULT clock_timestamp(),
    audit_event_id      bigint GENERATED BY DEFAULT AS IDENTITY,
    actor_type          text NOT NULL
                        CHECK (actor_type IN (
                            'system', 'owner', 'subscriber', 'migration',
                            'recovery', 'maintenance'
                        )),
    actor_id            text NOT NULL DEFAULT '',
    action              text NOT NULL CHECK (btrim(action) <> ''),
    object_type         text NOT NULL DEFAULT '',
    object_id           text NOT NULL DEFAULT '',
    result              text NOT NULL DEFAULT 'success'
                        CHECK (result IN ('success', 'failure', 'partial')),
    details             jsonb NOT NULL DEFAULT '{}'::jsonb
                        CHECK (jsonb_typeof(details) = 'object'),
    PRIMARY KEY (event_at, audit_event_id)
) PARTITION BY RANGE (event_at);

CREATE OR REPLACE FUNCTION ensure_event_partitions(
    p_start_month date,
    p_month_count integer
) RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    parent_name text;
    month_start date;
    month_end date;
    partition_name text;
    offset_no integer;
BEGIN
    IF p_start_month IS NULL THEN
        RAISE EXCEPTION 'p_start_month is required';
    END IF;
    IF p_month_count < 1 OR p_month_count > 36 THEN
        RAISE EXCEPTION 'p_month_count must be between 1 and 36';
    END IF;

    FOREACH parent_name IN ARRAY ARRAY[
        'job_events',
        'delivery_history',
        'source_scan_events',
        'audit_events'
    ]
    LOOP
        FOR offset_no IN 0..(p_month_count - 1)
        LOOP
            month_start := (
                date_trunc('month', p_start_month::timestamp)
                + make_interval(months => offset_no)
            )::date;
            month_end := (month_start + interval '1 month')::date;
            partition_name := format(
                '%s_%s',
                parent_name,
                to_char(month_start, 'YYYYMM')
            );
            EXECUTE format(
                'CREATE TABLE IF NOT EXISTS royells.%I PARTITION OF royells.%I '
                'FOR VALUES FROM (%L) TO (%L)',
                partition_name,
                parent_name,
                month_start,
                month_end
            );
        END LOOP;
    END LOOP;
END;
$$;

SELECT ensure_event_partitions(
    (date_trunc('month', current_date) - interval '1 month')::date,
    5
);

CREATE TABLE IF NOT EXISTS job_events_default
    PARTITION OF job_events DEFAULT;
CREATE TABLE IF NOT EXISTS delivery_history_default
    PARTITION OF delivery_history DEFAULT;
CREATE TABLE IF NOT EXISTS source_scan_events_default
    PARTITION OF source_scan_events DEFAULT;
CREATE TABLE IF NOT EXISTS audit_events_default
    PARTITION OF audit_events DEFAULT;

COMMENT ON SCHEMA royells IS
    'Transactional persistence for the Royells Telegram mirror bot.';
COMMENT ON TABLE job_queue_entries IS
    'Durable fair queue with expiring worker leases and fencing tokens.';
COMMENT ON TABLE delivery_intents IS
    'Pre-send journal used to reconcile ambiguous Telegram upload outcomes.';
COMMENT ON TABLE target_media_registry IS
    'Global non-partitioned media UID to target message authority.';
COMMENT ON TABLE source_scan_cursors IS
    'Exact per-source scan positions; cursor updates commit with job admission.';
COMMENT ON TABLE runtime_checkpoints IS
    'Versioned checksummed compatibility snapshots; not the primary queue authority.';
COMMENT ON TABLE redis_outbox IS
    'Transactional PostgreSQL-to-Redis projection events with idempotent publication.';

COMMIT;
