-- Royells v20 durable metrics samples.
-- Redis remains the fast projection; this table supports audit, comparison,
-- and migration validation without making Redis authoritative.

BEGIN;

SET LOCAL search_path = royells, public;
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '0';

CREATE TABLE IF NOT EXISTS metrics_samples (
    metric_sample_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_name        text NOT NULL CHECK (btrim(metric_name) <> ''),
    metric_value       double precision NOT NULL,
    labels             jsonb NOT NULL DEFAULT '{}'::jsonb
                       CHECK (jsonb_typeof(labels) = 'object'),
    observed_at        timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE INDEX IF NOT EXISTS idx_metrics_samples_name_time
    ON metrics_samples (metric_name, observed_at DESC, metric_sample_id DESC);

CREATE INDEX IF NOT EXISTS idx_metrics_samples_time_brin
    ON metrics_samples USING brin (observed_at)
    WITH (pages_per_range = 64);

COMMIT;
